name: baby_food_scanner
description: "A barcode scanner specialized for baby food products with nutritional analysis."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # OpenFoodFacts API
  openfoodfacts: ^3.23.0
  
  # Barcode scanning
  mobile_scanner: ^5.0.0
  
  # State management
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  
  # HTTP requests
  http: ^1.2.0
  
  # Data classes
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  
  # UI components
  cached_network_image: ^3.3.1
  
  # Permission handling
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code generation
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
